### ISSUE TITLE
[FAULT] report for #1674 (failed up process LHS upload Flavi_NS5_RdRp_20241206.tgz)

### ISSUE THREAD

**Issue by mwinokan** [m2ms/fragalysis-frontend#1705]
> Please describe the context for the fault, providing as much detail as possible. Items marked `[*]` are generally required.

### Fragalysis Stack
- Installation [*]: e.g. `DLS/Staging`
- Date and time (including timezone) [*]: e.g. `2025-03-10T10:15:00+0000`
- Stack version: e.g. `latest`
- Frontend version: e.g. `latest`
- Backend version: e.g. `latest`
- Browser: Microsoft Edge
- User/Anonymous: `tfb64483`

### Subject
- Target name: Flavi_NS5_RdRp
- Proposal Reference (Target Access String): e.g. `lb32633-1`
- Data directory: e.g. `/dls/labxchem/data/lb32627/lb32627-71/processing/analysis/xca_dec2024/upload-current/`

---

## Fault

LHS Upload to staging stack failed:

```
{"started": true, "finished": true, "status": "FAILED", "messages": ["INFO: Created TargetLoader for 'Flavi_NS5_RdRp_20241206.tgz' proposal_ref='lb32633-1'", "INFO: Decompressing 'Flavi_NS5_RdRp_20241206.tgz'", "INFO: Decompressed 'Flavi_NS5_RdRp_20241206.tgz'", "WARNING: Data minor version mismatch: 2.2 expected, 2.1 uploaded", "Failed to process 'Flavi_NS5_RdRp_20241206.tgz'", "FAILED"]}
```

**Comment by mwinokan** [comment]
@kaliif resolved this by bouncing the DB pod. 

@kaliif could you please share the part of the log that caused you to suspect this issue so we know how to spot it

**Comment by mwinokan** [comment]
`upload_1` has been resolved but `upload_2` is causing problems due to:

```
{"started": true, "finished": true, "status": "FAILED", "messages": ["INFO: Created TargetLoader for '20250307_Flavi_upload_2.tgz' proposal_ref='lb32633-1'", "INFO: Decompressing '20250310_Flavi_upload_2.tgz'", "INFO: Decompressed '20250310_Flavi_upload_2.tgz'", "WARNING: xtal_pdb referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive", "WARNING: xtal_mtz referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive", "WARNING: ligand_cif referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive", "WARNING: ligand_binding_events referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive", "Failed to process '20250310_Flavi_upload_2.tgz'", "FAILED"]}
```

I have spoken to Jasmin about this and we re-ran the collator and aligner. It is unclear to us why the dataset x0135 is an issue. this dataset has not been modified since the upload_1 and hence would not need to be included in the second upload.

@tdudgeon could you please investigate the two uploads in `/dls/labxchem/data/lb32627/lb32627-71/processing/analysis/xca_dec2024/upload-current/` and help us resolve this issue

**Comment by mwinokan** [comment]
@tdudgeon please describe what is wrong with the `upload_2` directory so that @ConorFWild can investigate

**Comment by tdudgeon** [comment]
Upload_2's are failing for me (I've tried this with 2 targets - code from `master` branch). I don't think this is the actual cause of the error described in this issue, but certainly stops it being investigated.

The reason why it is now failing doesn't make much sense to me. I don't see any recent changes in XCA or LNA that could be to blame.

What happens is that you get a `KeyError: 'CHIKV_MacB-x0270'` error from aligner which seems to be caused by the `assigned_xtalforms.yaml` file being empty in the `upload_2` version (it's OK in `upload_1`)

To reproduce run an `upload_1` but with a  couple of crystals excluded. Then run an `upload_2` but with those crystal no longer excluded. Collator runs OK but aligner fails.

**Comment by tdudgeon** [comment]
I think I tracked down the problem with running upload_2's.
The change to look at is the one in aligner.py
https://github.com/xchem/xchem-align/commit/a25daffe551cfbd54962509bdf1eef05fcb4987f#diff-98bcaf874d51d4c4153490f9a42f056d0453af355828fdf382f485c57f34abb8L427-R427

I still don't understand why users do not seem to have been affected by this

**Comment by mwinokan** [comment]
@kaliif the upload of `Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz` to staging Fragalysis via the uploader tool has failed.

The log is:

```
INFO: initialising logging at level 0 at 2025-03-12 10:15:40.287949
INFO: initialising logging at level 0 at 2025-03-12 10:15:40.288091
ERROR: ('Upload directory not found',)
ERROR: Upload directory not found
(/dls/science/groups/i04-1/software/xchem-align-staging/env_xchem_align) [tfb64483@cs05r-sc-serv-05 xca_dec2024]$ nano $SOFT/xchem-align-staging/src/xchemalign/uploader.py
(/dls/science/groups/i04-1/software/xchem-align-staging/env_xchem_align) [tfb64483@cs05r-sc-serv-05 xca_dec2024]$ python -m xchemalign.uploader -u staging -p lb32627-71 -t hmrulag2bt72lf3vyoi9mfl3gw4l2uj5
INFO: initialising logging at level 0 at 2025-03-12 10:17:16.757284
INFO: initialising logging at level 0 at 2025-03-12 10:17:16.757543
upload_current [] None
ERROR: ('Upload directory not found',)
ERROR: Upload directory not found
(/dls/science/groups/i04-1/software/xchem-align-staging/env_xchem_align) [tfb64483@cs05r-sc-serv-05 xca_dec2024]$ ls
aligner.log  setup.log	upload-current	upload-v2
(/dls/science/groups/i04-1/software/xchem-align-staging/env_xchem_align) [tfb64483@cs05r-sc-serv-05 xca_dec2024]$ nano $SOFT/xchem-align-staging/src/xchemalign/uploader.py
(/dls/science/groups/i04-1/software/xchem-align-staging/env_xchem_align) [tfb64483@cs05r-sc-serv-05 xca_dec2024]$ python -m xchemalign.uploader -u staging -p lb32627-71 -t hmrulag2bt72lf3vyoi9mfl3gw4l2uj5
INFO: initialising logging at level 0 at 2025-03-12 10:18:04.290833
INFO: initialising logging at level 0 at 2025-03-12 10:18:04.291051
INFO: Checking data version...
INFO: Using pigz for compression...
Compressing upload-current/upload_2: 81.8GB [00:07, 12.3GB/s]                                                                                                                                    
INFO: Tarball saved at: upload-current/Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz
Uploading: 561MB [00:14, 37.6MB/s]                                                                                                                                                               
INFO: Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz uploaded, processing:
INFO: Created TargetLoader for 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz' proposal_ref='lb32627-71'
INFO: Decompressing 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz'
INFO: Created TargetLoader for 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz' proposal_ref='lb32627-71'
INFO: Decompressing 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz'
INFO: Decompressed 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz'
INFO: Created TargetLoader for 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz' proposal_ref='lb32627-71'
INFO: Decompressing 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz'
INFO: Decompressed 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz'
WARNING: xtal_pdb referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive
WARNING: xtal_mtz referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive
WARNING: ligand_cif referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive
WARNING: ligand_binding_events referenced in meta_aligner.yaml: DNV2_NS5A-x0135 but not found in archive
Failed to process 'Flavi_NS5_RdRp_v2.2_upload_2_2025-03-12.tgz'
FAILED
```

I spoke with @tdudgeon and he believes that the collator and aligner ran correctly and that this might be a loader problem.

Namely, the `meta_aligner.yaml` references an `upload_1` dataset: `DNV2_NS5-x0135` whose status is `unchanged`. Hence it is not included in the crystallographic or aligned files of the archive (correctly). However the loader seems to throw an error because of this.

@kaliif could you please take a look? Due to SSH maintenance I can't share the tarball with you, but perhaps you are able to get it from the staging stack?

**Comment by kaliif** [comment]
@mwinokan the tarball doesn't appear to be on staging.

**Comment by mwinokan** [comment]
Thanks @kaliif. Forgot to broadcast here, but this upload_2 is now successfully in production

**Comment by tdudgeon** [comment]
@ConorFWild I fixed the path problems I found that were causing  the sites yamls (and other yamls) to be missing older versions. I'm not totally confident about all of these change so can you please review them (especially the ones with `CONOR_CHECK_THIS` comments).
The changes are in XCA and LNA, both on `issue_1674` branches.
Also, in LNA I removed some of the logging as it has become difficult to find the wheat among all the chaff. Feel free to reinstate any you think are important.

I have also supplied @kaliif with test data to allow him to work on #1674.

Note that #1674 and this issue (#1705) have become quite intertwined.

**Comment by ConorFWild** [comment]
@tdudgeon Did you run tests and see if they worked?

It seems more or less fine?

**Comment by tdudgeon** [comment]
@ConorFWild The tests are failing (see #1624). But they no more broken than before.
