### ISSUE TITLE
[CHILD OF #369] Buttons to skip to next compound/hit with same settings (both LHS and RHS)

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#384]
When investigating compounds (RHS) or hits (LHS), it will be extremely useful to be able to jump to the next (or previous) one with a single button-click, with all view settings applied.

![image](https://user-images.githubusercontent.com/33267937/85134961-35921b80-b235-11ea-97a3-ad456a776f0e.png)

Clicking the down button should turn off the one above while turning on the one below, transferring everything from the compound above to the one below:

1. remember the FULL display settings of the compound/hit _above_ the arrow.  
* For "F", if _any_ hits are displayed, consider that as _all_ hits displayed;  and if _no_ hits are displayed, then keep that setting.
* (Ideally) if any display settings were customised for either protein, ligand or contacts, then remember those too.
* (pragatically) if the previous point is too difficult, then don't bother.
2. turn off all displayed elements (except protein ribbon)
3. apply the settings of (1) above to the compound _below_ the arrow.

But do not reset the view.
Ditto for the up arrow, but just the other way round.

**Comment by phraenquex** [comment]
Nice arrows!  And great to have this, thanks!  But there's a remaining bug, so moving back to in progress.

Remaining bug:  turning on/off of the inspiration hits isn't working:  first bullet of point 1 in the spec. 

In the snapshot below:  I had all inspirations of one compound turned on (PAU-WEI-b9b69149-8), then I pressed the button circled red;  it proceeded as required, EXCEPT not all inspirations got turned on (they should have).

![image](https://user-images.githubusercontent.com/33267937/85402923-6aafae00-b554-11ea-99d4-c603c663b1ac.png)

The other way round is also wrong (snapshot below):  with not all fragments turned on, I clicked the down button (circled red):  it proceeded correctly, except now it should have turned OFF _all_ inspirations for that next compound (it didn't turn off anything).

![image](https://user-images.githubusercontent.com/33267937/85403123-c2e6b000-b554-11ea-8391-4704f85452b8.png)

**Comment by phraenquex** [comment]
Also:  if the Inspirations modal is open, it should also move when the arrow is clicked (up or down).

**Comment by phraenquex** [comment]
Correction:  this feature is ready for production, so moved to the "Issue pull request" swimlane.

I'll file a separate tickets for the bugs.

**Comment by phraenquex** [comment]
Left it in "In progress" - too much of the ticket was not implemented.  Please either do properly, or else explain why not.

**Comment by reskyner** [comment]
I don't like the up/down buttons being next to every molecule. The behaviour I'd expect from those buttons is something like that molecule moving up/down the list. I think the behaviour is nice, but I'd prefer it if there was a single set of two buttons (up and down or left and right) either above or below the navigator. Like this:

![image](https://user-images.githubusercontent.com/12764941/85434019-49af8300-b57d-11ea-9283-759c1715d7c0.png)

**Comment by reskyner** [comment]
Or this:

![Screenshot 2020-06-23 at 18 15 26](https://user-images.githubusercontent.com/12764941/85434147-854a4d00-b57d-11ea-9df2-e83c17f2d642.png)

**Comment by phraenquex** [comment]
More fixes:
- the arrows should show up _ONLY_ for highlighted (i.e. displayed) compounds
- if an arrow is clicked, ALL other compounds should be turned off, not only the compound that had the arrow
- the settings to be transferred onto the new compound should be taken from the compound whose arrow was clicked;  the settings of all other compounds should be ignored.

**Comment by phraenquex** [comment]
Commenting on Rachael's request:  I do NOT want the buttons down below, they should be displayed on the compound itself, because that's where my eye is when I use them.

**Comment by tibor-postek-m2ms** [comment]
solved in #369

**Comment by tibor-postek-m2ms** [comment]
merged in `rhs-filter` branch

**Comment by reskyner** [comment]
The bug with the colour on the background image still remains: https://github.com/m2ms/fragalysis-frontend/issues/396, but is listed under the next milestone. Will let @phraenquex decide wether this is fine to leave as it is for now.

**Comment by phraenquex** [comment]
Distressingly, the inspiration fragments are STILL not being turned off and on (as I specced 23 June).  But we can't wait - push to production.

I'll make a new ticket for the next milestone.
